// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDnj3-Y6DBD0SDtAaXi_478HdaFJmSh8Q',
    appId: '1:720493517129:web:54f5083c7840c291e42298',
    messagingSenderId: '720493517129',
    projectId: 'horizons-app-b9a65',
    authDomain: 'horizons-app-b9a65.firebaseapp.com',
    storageBucket: 'horizons-app-b9a65.firebasestorage.app',
    measurementId: 'G-WZT5ZP2RPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzWScmYHq9usVw6aherMuA6yTYLbUjSLw',
    appId: '1:720493517129:android:f6866f94767b583ae42298',
    messagingSenderId: '720493517129',
    projectId: 'horizons-app-b9a65',
    storageBucket: 'horizons-app-b9a65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxCPBoXIDgCsO48NvjIB6koWd70imhFD8',
    appId: '1:720493517129:ios:7e2aa01ac669abbde42298',
    messagingSenderId: '720493517129',
    projectId: 'horizons-app-b9a65',
    storageBucket: 'horizons-app-b9a65.firebasestorage.app',
    iosBundleId: 'com.example.movieClub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxCPBoXIDgCsO48NvjIB6koWd70imhFD8',
    appId: '1:720493517129:ios:7e2aa01ac669abbde42298',
    messagingSenderId: '720493517129',
    projectId: 'horizons-app-b9a65',
    storageBucket: 'horizons-app-b9a65.firebasestorage.app',
    iosBundleId: 'com.example.movieClub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDnj3-Y6DBD0SDtAaXi_478HdaFJmSh8Q',
    appId: '1:720493517129:web:6826492c845a7412e42298',
    messagingSenderId: '720493517129',
    projectId: 'horizons-app-b9a65',
    authDomain: 'horizons-app-b9a65.firebaseapp.com',
    storageBucket: 'horizons-app-b9a65.firebasestorage.app',
    measurementId: 'G-LJ27SYRBWW',
  );

}